    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - name: Get pip cache dir
            id: pip-cache
            run: |
              echo "::set-output name=dir::$(pip cache dir)"

          - name: pip cache
            uses: actions/cache@v2
            with:
              path: ${{ steps.pip-cache.outputs.dir }}
              key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
              restore-keys: |
                ${{ runner.os }}-pip-
          - uses: actions/checkout@v2
          - uses: education/autograding@v1
