    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - name: Setup Python
            uses: actions/setup-python@v1
            with:
              python-version: 3.7
          - uses: actions/cache@v2
            with:
              path: ~/.cache/pip
              key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
              restore-keys: |
                ${{ runner.os }}-pip-
                
          - name: Install Dependencies
            run: |
              pip install .
            
          - uses: actions/checkout@v2
          
          - uses: education/autograding@v1
